### ISSUE TITLE
Identity Domain

### ISSUE THREAD

**Issue by agh** [chef-partners/oracle-cloud-client#3]
Firstly this is *super* useful, and it's awesome that you put this together. Thanks :heart: :heart_eyes_cat:.

https://github.com/chef-partners/oracle-cloud-client/blob/master/lib/oraclecloud/client.rb#L93-L95

Unfortunately there's some behavioural differences between how 'Oracle Public Cloud' (e.g. cloud.oracle.com) works for a customer, versus 'Oracle Private Cloud' (running the software in your own datacenter, or indeed, within Oracle itself for internal usage).

In the above you've added `Compute-` to the identity domain, but that wouldn't be the case anywhere other than Oracle Public Cloud, I had to hack this out to avoid the following error:

```
/Users/agh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/oraclecloud-1.0.0/lib/oraclecloud/client.rb:247:in `raise_http_exception': Incorrect username or password (OracleCloud::Exception::HTTPError)
```

I can see a couple ways of solving this one:

  - We can add a boolean (maybe called `public_cloud`) which is enabled by default, and then make the addition of the identity domain name prefix (`Compute-`) only happen when that boolean is true. Obviously this preserves backwards compatibility. 

  - We can strip the prefix entirely and update documentation to reflect the fact that identity domains in Oracle Public Cloud are typically prefixed, but it's on the user to correctly state the entire domain.

Do you have a strong preference? I presume 'Option A' is more friendly, and thus preferred?

Thanks.

**Comment by adamleff** [comment]
Thanks for the issue report. The focus of this work (and the knife and test-kitchen plugins) was on the public cloud which is why this issue was not known.  

I think Option A is the safest at this point.  We'd probably want to rename `#compute_identity_domain ` to `#full_identity_domain` (for correctness' sake), add the conditional prepending there, and change the calls to it to use the new method name.  That should probably take care of it.

Want to take a stab at a PR?

**Comment by agh** [comment]
@adamleff Sure thing, and I agree that Option A makes the most sense. Look for a Pull Request from @afterglow in the next couple of days and we'll see if we can figure this out :+1:

**Comment by adamleff** [comment]
Closing issue in favor of in-progress PR #4
