### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by agh** [chef-partners/oracle-cloud-client#7]
A recent Pull Request (#4) to support private clouds actually introduced a Rubocop error which has been resolved by #6 but it'd be nice to gate against that kind of situation in future?

```
╭─agh at tower in ~/src/oracle/oracle-cloud-client on master✔ using ‹2.2.3›
╰─± rubocop
Inspecting 39 files
.....C.................................

Offenses:

lib/oraclecloud/client.rb:91:5: C: Use attr_reader to define trivial reader methods.
    def private_cloud?
    ^^^

39 files inspected, 1 offense detected
```

Was thinking it might be a good idea to wire up Travis CI to execute Rubocop and RSpec?

@adamleff What do you think and would you be willing to whack the appropriate button over in [Travis CI](travis-ci.org) since I think it requires a committer bit to enable, plus the requisite bit of YAML in the repository?

**Comment by adamleff** [comment]
I have a list of repos that I need to get under Travis oversight and this is one of them.  I'll take care of this soon.

**Comment by adamleff** [comment]
Added to travis.
